In [1]:
from interpolant import AnyOrderMaskInsertionInterpolant
import torch
from schedule import LinearSchedule

In [34]:
mask_token = 0
pad_token = 3
max_length = 5
mask_schedule = LinearSchedule()
interpolant = AnyOrderMaskInsertionInterpolant(mask_schedule, 3, 0, 3, 5)
t = torch.Tensor([0.4])
x1 = torch.Tensor([[1, 2, 3, 3, 3], [1, 2, 2, 1, 3]]).to(torch.int64)
xt, st = interpolant.sample_interpolant(t, x1)
xt, st

(tensor([[0, 3, 3, 3, 3],
         [0, 0, 3, 3, 3]]),
 tensor([[0, 6, 6, 6, 6],
         [0, 3, 6, 6, 6]]))

In [36]:
reparametrised_rate = interpolant.reparametrised_conditional_rate(xt, st, t, x1)

torch.Size([2, 5, 3]) torch.Size([2, 1, 5]) torch.Size([2, 5]) torch.Size([2, 5, 1])
tensor([[1, 2, 2, 2, 2],
        [1, 1, 2, 2, 2]]) tensor([[[1.6667],
         [0.0000],
         [0.0000],
         [0.0000],
         [0.0000]],

        [[1.6667],
         [1.6667],
         [0.0000],
         [0.0000],
         [0.0000]]])
sorted_st tensor([[0, 6, 6, 6, 6],
        [0, 3, 6, 6, 6]])
sorted_clamped tensor([[0, 2, 2, 2, 2],
        [0, 3, 4, 4, 4]])
padded tensor([[-1,  0,  2,  2,  2,  2,  2],
        [-1,  0,  3,  4,  4,  4,  4]])
gap_counts tensor([[0, 1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0, 0]])


In [38]:
reparametrised_rate.length_posterior

tensor([[[1., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0.]],

        [[1., 0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0.]]])